# Generated by Django 5.2.6 on 2025-10-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.JSONField()),
                ('pickup', models.JSONField()),
                ('dropoff', models.JSONField()),
                ('hours_used', models.FloatField()),
                ('route_geojson', models.JSONField()),
                ('summary', models.JSONField()),
                ('stops', models.JSONField()),
                ('logs', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
